name: Deploy to GitHub Pages
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04

    env:
      MAIN_BRANCH: main
      PAGES_BRANCH: pages

    steps:

      # Install NodeJs for building the project
      - name: Install NodeJs
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      # Checkout repo from main branch (unless we already have it)
      - name: Checkout Main Project Branch
        uses: actions/checkout@v2
        if: hashFiles('.git/config').size == 0

      # Build the project
      - name: Build Project
        run: |
          npm ci
          npm run build

      # Push
      - name: Push Build to Pages Branch
        run: |
          git pull
          git checkout -B ${PAGES_BRANCH}
          find . -mindepth 1 -regextype posix-extended ! -regex '^./(.git|dist)($|/.*)' -delete
          mv ./dist/* . && rm -r ./dist
          touch .nojekyll
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add . */.*
          git commit -m "${GITHUB_EVENT_NAME}-${GITHUB_REF_NAME}-${GITHUB_ACTOR}"
          git push -f origin pages
